name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [main] # branch to trigger deployment

jobs:
  pages:
    runs-on: ubuntu-20.04
    permissions:
      pages: write
      id-token: write
      contents: write
      pull-requests: write
    steps:
    - uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "pip install . sphinx sphinx-tabs sphinx_rtd_theme sphinx-panels"
        docs-folder: "docs/"
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html/